version: '3'

services:
  rabbitmq-svc:
    image: rabbitmq:3.10-management
    container_name: rabbitmq-svc
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
     - ./data:/var/run/rabbitmq
    env_file:
      - .env
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
